### ISSUE TITLE
movemouse not work in the virtualbox,os is windows

### ISSUE THREAD

**Issue by goldboy123** [go-vgo/robotgo#250] opened 2019-12-10 12:43 UTC
movemouse function doesn't not work in the virtualbox,os is windows

**Comment by vcaesar** [comment] 2019-12-10 14:25
Closing is due to can't reproduce and non-standard.

**Closed by vcaesar** 2019-12-10 14:25 UTC

**Comment by dlsniper** [comment] 2020-01-10 07:30
I had the same issue as above.

Workaround:
At first the program did not worked, it was just hanging there.
Then I closed the app, turned off the "Mouse integration" feature for the VM, and started the app again, and the integration worked fine.

Let me know if I should send a PR to change this in the README or you'd prefer to reproduce this (see the details below).

P.S. Thanks for this awesome project!

Steps to reproduce:
- install VirtualBox 6.1 on a Windows 10 amd64 Host machine
- install Ubuntu 18.04.3 amd64 as a Guest OS
- use Go 1.13.5 to compile a sample app like this:
```go
package main

import "github.com/go-vgo/robotgo"

func main() {
	robotgo.MoveMouseSmooth(100, 200, 1.0, 100.0)
}
```
