### ISSUE TITLE
Issue when run on macOS ' identifier "_Ctype_char" may conflict with identifiers generated by cgo .../robotgo.go:566:30: identifier "_Ctype_char" may conflic'

### ISSUE THREAD

**Issue by gcstang** [go-vgo/robotgo#191] opened 2019-01-20 18:58 UTC
- Robotgo version (or commit ref):
robotgo@v0.0.0-20190120172534-832a8634abd0

- Go version:
1.12beta2
- Gcc version:
8.2.0
- Operating system and bit:
macOS High Sierra 10.13.6
- Resolution:
N/A
- Provide example code:

```Go
package main

import (
	"github.com/go-vgo/robotgo"
)
func main() {
	robotgo.ScrollMouse(10, "up")
	robotgo.MouseClick("left", true)
	robotgo.MoveMouseSmooth(100, 200, 1.0, 100.0)
}
```
- Log gist:

## Description
../../../../pkg/mod/github.com/go-vgo/robotgo@v0.0.0-20190120172534-832a8634abd0/robotgo.go:529:22: identifier "_Ctype_char" may conflict with identifiers generated by cgo
../../../../pkg/mod/github.com/go-vgo/robotgo@v0.0.0-20190120172534-832a8634abd0/robotgo.go:566:30: identifier "_Ctype_char" may conflict with identifiers generated by cgo
...

**Comment by vcaesar** [comment] 2019-01-23 23:02
Closing is due to can't reproduce.

**Comment by lukeng** [comment] 2019-01-24 04:37
I also encountered this issue.
seems the code can be changed from _Ctype_char to C.char:
https://groups.google.com/forum/#!topic/golang-nuts/FxOqMSE6qek

**Comment by gcstang** [comment] 2019-01-24 14:57
Issue for me turned out to be latest version of Go 1.12beta2 went back to 1.11.5 and it's working.

**Comment by vcaesar** [comment] 2019-01-24 17:54
There is no test in go1.12, it will be tested and fixed after the official release.

**Closed** 2019-02-26 16:09 UTC
Labels: Mac
