### ISSUE TITLE
Windows 10 GetScreenSize too small

### ISSUE THREAD

**Issue by jsnider3** [go-vgo/robotgo#129] opened 2018-04-20 06:12 UTC
- Robotgo version (or commit ref):
- Go version: go version go1.10.1 windows/amd64
- Gcc version: gcc version 7.3.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
- Operating system and bit: Windows 10, 64-bit
![test](https://user-images.githubusercontent.com/1146538/39033421-e5095d6e-443f-11e8-8fb2-45b6573ca488.png)
![correct](https://user-images.githubusercontent.com/1146538/39033422-e514b9d4-443f-11e8-8a96-005b9318da20.PNG)

- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [X] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code: 
    ```package main

    import "github.com/go-vgo/robotgo"

    func main() {
    	width, height := robotgo.GetScreenSize()
    	bitmap := robotgo.CaptureScreen(0, 0, width, height)

    	robotgo.SaveBitmap(bitmap, "test.png")


    	bitmap = robotgo.CaptureScreen()

    	robotgo.SaveBitmap(bitmap, "test2.png")
    } 

    ```

## Description

I'm trying to take a picture of the entire screen, I try to do that by calling GetScreenSize and passing
that as the args to CaptureScreen, but as you can see from the attached test.png and correct.png, that's not the correct size.

**Comment by vcaesar** [comment] 2018-04-20 11:12
I tested normally on Windows 7, and this is using a method. I will test it on windows 10.

**Comment by vcaesar** [comment] 2018-04-22 15:05
I tested on window10, and it works. Closing because there is no obvious robotgo problem( On my computer windows7 & windows10 64bit is normal). If you are convinced there is a robotgo problem, please tell us precisely how we can reproduce the problem ourselves.

**Closed by vcaesar** 2018-04-22 15:05 UTC

**Comment by vcaesar** [comment] 2018-04-22 15:47
What is your screen size and resolution?

**Comment by vcaesar** [comment] 2018-07-09 15:48
I added the GetScaleSize method on windows.

**Comment by vcaesar** [comment] 2018-07-20 15:14
If you set scale, please use the following code, currently only valid for windows:
```Go
package main

import (
   "fmt"

   "github.com/go-vgo/robotgo"
)

func main() {
	width, height := robotgo.GetScaleSize()
        fmt.Println("GetScreenSize: ", width, height)

	bitmap := robotgo.CaptureScreen(0, 0, width, height)
	robotgo.SaveBitmap(bitmap, "test.png")

        s := robotgo.Scale()
	bit1 := robotgo..CaptureScreen(0, 0, 35* s / 100, 25* s / 100)
	robotgo.SaveBitmap(bit1, "test2.png")
} 
```
