### ISSUE TITLE
KeyTap is not working on OSX

### ISSUE THREAD

**Issue by miagile** [go-vgo/robotgo#171] opened 2018-10-06 10:05 UTC
I'm running the code below on latest OSX (Mojave, 10.14). The issue is that the "arrow down" is not working. I'm testing this by having an instance of Chrome window with a "Select" element open and nothing is moving. `robotgo.TypeString("Hello World")` is not working either but I was   interested in KeyTab thus I make this issue about KeyTap. 

func main(){
for i := 0 ;i < 10; i ++{
  time.Sleep(5 * time.Second)
  robotgo.KeyTap("down")
  fmt.Printf("SUCESS")
}
  return
}

**Comment by miagile** [comment] 2018-10-06 11:02
Probably related to https://forums.developer.apple.com/thread/103992

**Comment by vcaesar** [comment] 2018-10-06 16:57
Closing is due to can't reproduce.

**Closed by vcaesar** 2018-10-06 16:57 UTC
