### ISSUE TITLE
XkbGetKeyboard failed to locate a valid keyboard!

### ISSUE THREAD

**Issue by imtiyazs** [go-vgo/robotgo#160] opened 2018-09-01 09:29 UTC
- Robotgo version (or commit ref): Latest from today
- Go version: 1.10.4
- Gcc version: 7.2.0
- Operating system and bit: Ubuntu 17.10 
- Can you reproduce the bug (Check below code):
  - [ ] Yes

```Go
package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
)

func main() {
	fmt.Println(robotgo.GetTitle())
}

```
- Log gist:
No protocol specified
on_library_load [441]: XOpenDisplay failure!
load_input_helper [1892]: XkbGetKeyboard failed to locate a valid keyboard!
signal: segmentation fault (core dumped)

## Description
The program doesnt execute and exits with above log mentioned of  XkbGetKeyboard failed to locate a valid Keyboard!.
...

## System information
Dell Vostro 15 (2017 Model)
Gnome 3.26.2
64 Bit

**Comment by vcaesar** [comment] 2018-09-06 14:42
I did not reproduce the problem in the Ubuntu 14.04, I will test it on 17.04 .

**Comment by imtiyazs** [comment] 2018-09-06 14:48
Yes please. Thank u.

**Comment by FloThinksPi** [comment] 2018-11-05 20:10
Also having this on fedora 29
![image](https://user-images.githubusercontent.com/5863788/48023738-f0dc6e00-e13e-11e8-9871-7ead07063694.png)

**Comment by Pheric** [comment] 2019-03-15 04:02
I'm having this same issue with examples from readme.md. Running arch linux and X11

**Comment by baogume** [comment] 2019-03-18 07:45
> I'm having this same issue with examples from readme.md. Running centos 7.4 and X11

**Comment by vcaesar** [comment] 2019-03-18 13:45
Can only reproduce ``` fmt.Println(robotgo.GetTitle(pid)) ```, Closing is due to duplicate ( #165 ) and will be fixed soon.

**Closed by vcaesar** 2019-03-18 13:45 UTC
Labels: enhancement

**Comment by baolitoumu** [comment] 2019-04-15 07:36
你只需在服务器的display上运行，就会报错

**Comment by baolitoumu** [comment] 2019-04-15 07:48
DISPLAY=:1 xx 会产生这样的报错，XkbGetKeyboard failed to locate a valid keyboard 。并不致命。

**Comment by sriveros95** [comment] 2020-05-22 18:33
Having this issue on fedora following readme instructions

**Comment by sriveros95** [comment] 2020-05-22 19:09
> Having this issue on fedora following readme instructions

Sorry, I tried with xorg and it works :)

**Comment by c0nect** [comment] 2022-03-29 01:41
april 2022 and this issue has not been resolved so far :(

**Comment by rajkumarks7** [comment] 2022-06-22 10:12
any update on this error ? @vcaesar

**Comment by Arnwaltur** [comment] 2022-09-06 07:48
Same error here with Ubuntu 22.04 and Debian 11.

**Comment by LuSrackhall** [comment] 2024-08-24 06:22
Ubuntu 24.04 Desktop edition also has this issue, and it remains unresolved to this day.

**Comment by AquilaFasciata** [comment] 2024-10-02 03:57
This issue still doesn't appear to be fixed? Is this issue supposed to be closed?

**Comment by Arnwaltur** [comment] 2024-10-02 07:15
Not fixed.
