### ISSUE TITLE
BadWindow error  when invoking GetTitle() on Ubuntu 16.04

### ISSUE THREAD

**Issue by alanfo** [go-vgo/robotgo#165] opened 2018-09-20 12:10 UTC
- Robotgo version (or commit ref): 0.50.0.666
- Go version: 1.11
- Gcc version: 5.4.0
- Operating system and bit: Ubuntu 16.04, 64-bit
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```go
package main

import (
    "fmt"
    "github.com/go-vgo/robotgo"
)

func main() {
    fmt.Println(robotgo.Version)

    fpid, err := robotgo.FindIds("gedit")
    if err == nil && len(fpid) > 0 {
        fmt.Println("Array length =", len(fpid))
        robotgo.ActivePID(fpid[0])
        tl := robotgo.GetTitle(fpid[0])
        fmt.Println("pid[0] title is: ", tl)
    }
}
```
- Log gist:

```
v0.50.0.666, The Appalachian Mountains!
Array length = 1
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x2349
  Serial number of failed request:  7
  Current serial number in output stream:  7
exit status 1
```
## Description
I tried to 'active' a gedit window I have open but I received a similar error message to #140 which I thought had been fixed.

A possible issue is that my GCC is version 5.4.0 which apparently is the latest version officially supported by Ubuntu 16.04. GCC is now up to v8.2, of course.

For various reasons I don't want to update to a later version of Ubuntu at the present time or to risk breaking the distribution by using an unsupported version of GCC.

Could this be the reason for the problem or is it a bug?

...

**Comment by vcaesar** [comment] 2018-09-20 16:12
I tested this code on Ubuntu 15.04 and can't reproduce your problem.

**Comment by vcaesar** [comment] 2018-09-20 16:26
This is a problem with GetTitle(), which is not yet fully supported on linux.

**Comment by alanfo** [comment] 2018-09-20 17:44
OK, thanks for looking into it.

It hadn't dawned on me that GetTitle() rather than ActivePID() could be the problem. 

Need more sleep!

**Comment by imtiyazs** [comment] 2018-09-24 12:05
I suggest there should be error handling for _**robotgo.ActivePID(fpid[i])**_  and _**robotgo.GetTitle(fpid[i])**_ . Because in few cases where there are multiple sub process of one program, for example Google chrome, there are more than 2 process out of which 1 is main window and others are extended process for host, extensions and sub modules. In this case, the _**robotgo.FindIds("chrome")**_ returns a huge array and to get active window i need to use for loop.. Hence it crashes if PID is not a window.

**Comment by vcaesar** [comment] 2018-09-24 17:42
I will consider how to make it more perfect.

**Comment by vcaesar** [comment] 2019-03-18 17:35
@imtiyazs Not because of error handling, and the problem parameter you mentioned is not have pid (#160 ), you misled me twice. But because your parameter is pid instead of xid, no conversion. It will be fixed.

**Closed** 2019-03-19 14:30 UTC
Labels: enhancement
