### ISSUE TITLE
 fatal error: 'screen/goScreen.h' file not found

### ISSUE THREAD

**Issue by emailtovamos** [go-vgo/robotgo#167] opened 2018-09-23 17:14 UTC
I am getting the following error: 

```# github.com/drawGo/vendor/github.com/go-vgo/robotgo
vendor/github.com/go-vgo/robotgo/robotgo.go:44:10: fatal error: 'screen/goScreen.h' file not found
#include "screen/goScreen.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

- Robotgo version (or commit ref): latest
- Go version: go version go1.10 darwin/amd64
- Gcc version:

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

- Operating system and bit: Mac OS High Sierra 10.13.2
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go): 
  - [* ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go

package main

import (
	"fmt"

	"github.com/go-vgo/robotgo"
	// "go-vgo/robotgo"
)

func main() {
	ver := robotgo.GetVersion()
	fmt.Println("robotgo version is: ", ver)
}

```
- Log gist:

## Description
Not sure what is missing. Is it a problem with ```gcc```? 
...

**Comment by vcaesar** [comment] 2018-09-24 17:46
I can't reproduce the problem at 10.13.6, please make sure xcode-select tool is installed correctly.

**Comment by vcaesar** [comment] 2018-09-28 16:56
Closing is due to can't reproduce.

**Closed by vcaesar** 2018-09-28 16:56 UTC
