### ISSUE TITLE
run 'go get github.com/go-vgo/robotgo '  failed  on macos

### ISSUE THREAD

**Issue by linuxsky** [go-vgo/robotgo#49] opened 2017-02-28 03:38 UTC
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:56:91: error: expected a type
- (void)executeWithArguments:(nullable NSArray<NSString *> *)arguments completionHandler:(nullable NSUserUnixTaskCompletionHandler)handler;
                                                                                          ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:71:32: error: expected a type
- (void)executeWithAppleEvent:(nullable NSAppleEventDescriptor *)event completionHandler:(nullable NSUserAppleScriptTaskCompletionHandler)handler;
                               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:71:91: error: expected a type
- (void)executeWithAppleEvent:(nullable NSAppleEventDescriptor *)event completionHandler:(nullable NSUserAppleScriptTaskCompletionHandler)handler;
                                                                                          ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:85:12: error: unknown property attribute 'nullable'
@property (nullable, copy) NSDictionary<NSString *, id> *variables;
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:85:50: error: expected '>'
@property (nullable, copy) NSDictionary<NSString *, id> *variables;
                                                 ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:85:51: error: expected member name or ';' after declaration specifiers
@property (nullable, copy) NSDictionary<NSString *, id> *variables;
                           ~~~~~~~~~~~~           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:85:1: error: property requires fields to be named
@property (nullable, copy) NSDictionary<NSString *, id> *variables;
^                          ~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:85:53: error: interface type cannot be statically allocated
@property (nullable, copy) NSDictionary<NSString *, id> *variables;
                                                    ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:85:55: error: expected ';' at end of declaration list
@property (nullable, copy) NSDictionary<NSString *, id> *variables;
                                                      ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:85:55: error: expected identifier or '('
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:89:27: error: expected a type
- (void)executeWithInput:(nullable id <NSSecureCoding>)input completionHandler:(nullable NSUserAutomatorTaskCompletionHandler)handler;
                          ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:89:81: error: expected a type
- (void)executeWithInput:(nullable id <NSSecureCoding>)input completionHandler:(nullable NSUserAutomatorTaskCompletionHandler)handler;
                                                                                ^
In file included from ../github.com/go-vgo/robotgo/robotgo.go:38:
In file included from ./key/goKey.h:14:
In file included from ./key/keypress_c.h:1:
In file included from ./key/keypress.h:6:
In file included from ./key/keycode.h:14:
In file included from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:29:
In file included from /System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/HIToolbox.h:240:
In file included from /System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/IMKInputSession.h:23:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:175:
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:13:62: error: expected ';' after @class
@class NSMutableDictionary, NSString, NSOperationQueue, NSSet<ObjectType>, NSLock, NSError;
                                                             ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:13:63: error: cannot find protocol declaration for 'ObjectType'
@class NSMutableDictionary, NSString, NSOperationQueue, NSSet<ObjectType>, NSLock, NSError;
                                                              ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:13:74: error: expected identifier or '('
@class NSMutableDictionary, NSString, NSOperationQueue, NSSet<ObjectType>, NSLock, NSError;
                                                                         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:64:12: error: unknown property attribute 'nullable'
@property (nullable, readonly, copy) NSString *serviceName;
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:74:12: error: unknown property attribute 'nullable'
@property (nullable, retain) NSXPCInterface *exportedInterface;
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:77:12: error: unknown property attribute 'nullable'
@property (nullable, retain) id exportedObject;
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:80:12: error: unknown property attribute 'nullable'
@property (nullable, retain) NSXPCInterface *remoteObjectInterface;
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:89:12: error: unknown property attribute 'nullable'
@property (nullable, copy) void (^interruptionHandler)(void);
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:94:12: error: unknown property attribute 'nullable'
@property (nullable, copy) void (^invalidationHandler)(void);
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:138:12: error: unknown property attribute 'nullable'
@property (nullable, assign) id <NSXPCListenerDelegate> delegate;
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:180:27: error: cannot find protocol declaration for 'Class'
- (void)setClasses:(NSSet<Class> *)classes forSelector:(SEL)sel argumentIndex:(NSUInteger)arg ofReply:(BOOL)ofReply;
                          ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:181:10: error: cannot find protocol declaration for 'Class'
- (NSSet<Class> *)classesForSelector:(SEL)sel argumentIndex:(NSUInteger)arg ofReply:(BOOL)ofReply;
         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:185:4: error: expected a type
- (nullable NSXPCInterface *)interfaceForSelector:(SEL)sel argumentIndex:(NSUInteger)arg ofReply:(BOOL)ofReply;
   ^
3077 errors generated.

**Comment by vCaesar** [comment] 2017-02-28 06:46
@linuxsky  You should give more information,I do not know in which system to reproduce it.

**Comment by vCaesar** [comment] 2017-02-28 06:48
Please make sure Golang,GCC,zlib and libpng is installed correctly before installing RobotGo.

**Comment by vCaesar** [comment] 2017-03-01 07:07
Closing because there is no obvious robotgo problem(There is no problem with my mac.). If you are convinced there is a robotgo problem, please tell us precisely how we can reproduce the problem ourselves.

**Closed by vCaesar** 2017-03-01 07:07 UTC
