### ISSUE TITLE
build error in windows

### ISSUE THREAD

**Issue by Mehedee-Hassan** [go-vgo/robotgo#27] opened 2016-11-24 21:42 UTC
I was trying to build "go-vgo/robotgo" library .

I have followed each step like downloading "mingw"(32bit) and adding "zlib,pnglib" from zlib&libpng Windows32 GCC's Course as stated. but when i try to get it from cmd using this command,

`go get github.com/go-vgo/robotgo`

it shows a enormous list of error.

Can anyone help me please. I am using windows 10 (64 bit) and go 1.7.3 (x86).

Errors copied from the cmd is given below,

>G:\ProgramFiles\Go32>go get github.com/go-vgo/robotgo 
> github.com/go-vgo/robotgo In file included from
> ./mouse/goMouse.h:12:0,
>                  from src\github.com\go-vgo\robotgo\robotgo.go:24: ./mouse/mouse_c.h: In function 'moveMouse': ./mouse/mouse_c.h:116:2:
> error: unknown type name 'INPUT' ./mouse/mouse_c.h:117:12: error:
> request for member 'type' in something not a structure or union
> ./mouse/mouse_c.h:117:20: error: 'INPUT_MOUSE' undeclared (first use
> in this function) ./mouse/mouse_c.h:117:20: note: each undeclared
> identifier is reported only once for each function it appears in
> ./mouse/mouse_c.h:118:12: error: request for member 'mi' in something
> not a structure or union ./mouse/mouse_c.h:119:12: error: request for
> member 'mi' in something not a structure or union
> ./mouse/mouse_c.h:120:12: error: request for member 'mi' in something
> not a structure or union ./mouse/mouse_c.h:121:12: error: request for
> member 'mi' in something not a structure or union
> ./mouse/mouse_c.h:122:12: error: request for member 'mi' in something
> not a structure or union ./mouse/mouse_c.h:123:12: error: request for
> member 'mi' in something not a structure or union ./mouse/mouse_c.h:
> In function 'scrollMouse': ./mouse/mouse_c.h:249:3: error: unknown
> type name 'INPUT' ./mouse/mouse_c.h:293:19: error: request for member
> 'type' in something not a structure or union ./mouse/mouse_c.h:293:27:
> error: 'INPUT_MOUSE' undeclared (first use in this function)
> ./mouse/mouse_c.h:294:19: error: request for member 'mi' in something
> not a structure or union ./mouse/mouse_c.h:295:19: error: request for
> member 'mi' in something not a structure or union
> ./mouse/mouse_c.h:296:19: error: request for member 'mi' in something
> not a structure or union ./mouse/mouse_c.h:297:19: error: request for
> member 'mi' in something not a structure or union
> ./mouse/mouse_c.h:298:19: error: request for member 'mi' in something
> not a structure or union ./mouse/mouse_c.h:299:19: error: request for
> member 'mi' in something not a structure or union In file included
> from ./key/keypress.h:6:0,
>                  from ./key/keypress_c.h:1,
>                  from ./key/goKey.h:14,
>                  from src\github.com\go-vgo\robotgo\robotgo.go:25: ./key/keycode.h: At top level: ./key/keycode.h:249:24: error:
> 'VK_VOLUME_MUTE' undeclared here (not in a function)
> ./key/keycode.h:250:24: error: 'VK_VOLUME_DOWN' undeclared here (not
> in a function) ./key/keycode.h:251:22: error: 'VK_VOLUME_UP'
> undeclared here (not in a function) ./key/keycode.h:252:17: error:
> 'VK_MEDIA_PLAY_PAUSE' undeclared here (not in a function)
> ./key/keycode.h:253:17: error: 'VK_MEDIA_STOP' undeclared here (not in
> a function) ./key/keycode.h:255:17: error: 'VK_MEDIA_PREV_TRACK'
> undeclared here (not in a function) ./key/keycode.h:256:17: error:
> 'VK_MEDIA_NEXT_TRACK' undeclared here (not in a function) In file
> included from ./key/goKey.h:14:0,
>                  from src\github.com\go-vgo\robotgo\robotgo.go:25: ./key/keypress_c.h: In function 'win32KeyEvent':
> ./key/keypress_c.h:57:39: error: 'MAPVK_VK_TO_VSC' undeclared (first
> use in this function) ./key/keypress_c.h:86:8: error:
> 'VK_BROWSER_BACK' undeclared (first use in this function)
> ./key/keypress_c.h:87:8: error: 'VK_BROWSER_FORWARD' undeclared (first
> use in this function) ./key/keypress_c.h:88:8: error:
> 'VK_BROWSER_REFRESH' undeclared (first use in this function)
> ./key/keypress_c.h:89:8: error: 'VK_BROWSER_STOP' undeclared (first
> use in this function) ./key/keypress_c.h:90:8: error:
> 'VK_BROWSER_SEARCH' undeclared (first use in this function)
> ./key/keypress_c.h:91:8: error: 'VK_BROWSER_FAVORITES' undeclared
> (first use in this function) ./key/keypress_c.h:92:8: error:
> 'VK_BROWSER_HOME' undeclared (first use in this function)
> ./key/keypress_c.h:93:8: error: 'VK_LAUNCH_MAIL' undeclared (first use
> in this function) In file included from ./event/goEvent.h:29:0,
>                  from src\github.com\go-vgo\robotgo\robotgo.go:27: ./event/hook/windows/input_c.h: At top level:
> ./event/hook/windows/input_c.h:31:27: error: 'VK_OEM_MINUS' undeclared
> here (not in a function) ./event/hook/windows/input_c.h:32:27: error:
> 'VK_OEM_PLUS' undeclared here (not in a function)
> ./event/hook/windows/input_c.h:70:24: error: 'VK_OEM_COMMA' undeclared
> here (not in a function) ./event/hook/windows/input_c.h:71:24: error:
> 'VK_OEM_PERIOD' undeclared here (not in a function)
> ./event/hook/windows/input_c.h:183:28: error: 'VK_LAUNCH_APP2'
> undeclared here (not in a function)
> ./event/hook/windows/input_c.h:200:30: error: 'VK_BROWSER_HOME'
> undeclared here (not in a function) In file included from
> ./event/goEvent.h:29:0,
>                  from src\github.com\go-vgo\robotgo\robotgo.go:27: ./event/hook/windows/input_c.h:251:32: error: 'VK_BROWSER_SEARCH'
> undeclared here (not in a function)
> ./event/hook/windows/input_c.h:252:30: error: 'VK_BROWSER_FAVORITES'
> undeclared here (not in a function)
> ./event/hook/windows/input_c.h:253:30: error: 'VK_BROWSER_REFRESH'
> undeclared here (not in a function)
> ./event/hook/windows/input_c.h:254:30: error: 'VK_BROWSER_STOP'
> undeclared here (not in a function)
> ./event/hook/windows/input_c.h:255:30: error: 'VK_BROWSER_FORWARD'
> undeclared here (not in a function)
> ./event/hook/windows/input_c.h:256:30: error: 'VK_BROWSER_BACK'
> undeclared here (not in a function)
> ./event/hook/windows/input_c.h:258:30: error: 'VK_LAUNCH_APP1'
> undeclared here (not in a function)
> ./event/hook/windows/input_c.h:259:30: error: 'VK_LAUNCH_MEDIA_SELECT'
> undeclared here (not in a function) In file included from
> ./event/goEvent.h:30:0,
>                  from src\github.com\go-vgo\robotgo\robotgo.go:27: ./event/hook/windows/hook_c.h: In function 'initialize_modifiers':
> ./event/hook/windows/hook_c.h:90:18: error: 'VK_XBUTTON1' undeclared
> (first use in this function) ./event/hook/windows/hook_c.h:91:18:
> error: 'VK_XBUTTON2' undeclared (first use in this function)
> ./event/hook/windows/hook_c.h: In function 'mouse_hook_event_proc':
> ./event/hook/windows/hook_c.h:509:8: error: 'WM_XBUTTONDOWN'
> undeclared (first use in this function)
> ./event/hook/windows/hook_c.h:510:8: error: 'WM_NCXBUTTONDOWN'
> undeclared (first use in this function)
> ./event/hook/windows/hook_c.h:511:37: error: 'XBUTTON1' undeclared
> (first use in this function) ./event/hook/windows/hook_c.h:515:42:
> error: 'XBUTTON2' undeclared (first use in this function)
> ./event/hook/windows/hook_c.h:551:8: error: 'WM_XBUTTONUP' undeclared
> (first use in this function) ./event/hook/windows/hook_c.h:552:8:
> error: 'WM_NCXBUTTONUP' undeclared (first use in this function) In
> file included from ./event/goEvent.h:30:0,
>                  from src\github.com\go-vgo\robotgo\robotgo.go:27: ./event/hook/windows/hook_c.h: In function 'win_hook_event_proc':
> ./event/hook/windows/hook_c.h:616:8: error: 'EVENT_OBJECT_NAMECHANGE'
> undeclared (first use in this function) ./event/hook/windows/hook_c.h:
> In function 'hook_run': ./event/hook/windows/hook_c.h:684:4: error:
> 'EVENT_OBJECT_NAMECHANGE' undeclared (first use in this function)
> ./event/hook/windows/hook_c.h:688:4: error: 'WINEVENT_OUTOFCONTEXT'
> undeclared (first use in this function)
> ./event/hook/windows/hook_c.h:688:28: error: 'WINEVENT_SKIPOWNPROCESS'
> undeclared (first use in this function)
> ./event/hook/windows/hook_c.h:688:26: error: invalid operands to
> binary | (have 'const uint16_t (*)[2]' and 'const uint16_t (*)[2]') In
> file included from ./event/goEvent.h:31:0,
>                  from src\github.com\go-vgo\robotgo\robotgo.go:27: ./event/hook/windows/event_c.h: In function 'hook_post_event':
> ./event/hook/windows/event_c.h:57:2: error: unknown type name 'INPUT'
> ./event/hook/windows/event_c.h:57:32: error: 'INPUT' undeclared (first
> use in this function) ./event/hook/windows/event_c.h:57:39: error:
> invalid operands to binary * (have 'const uint16_t (*)[2]' and 'int')
> ./event/hook/windows/event_c.h:63:24: error: request for member 'type'
> in something not a structure or union
> ./event/hook/windows/event_c.h:63:32: error: 'INPUT_KEYBOARD'
> undeclared (first use in this function)
> ./event/hook/windows/event_c.h:64:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:64:27: error: request for member 'wVk'
> in something not a structure or union
> ./event/hook/windows/event_c.h:65:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:65:27: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:66:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:66:27: error: request for member 'time'
> in something not a structure or union
> ./event/hook/windows/event_c.h:73:22: error: request for member 'type'
> in something not a structure or union
> ./event/hook/windows/event_c.h:73:30: error: 'INPUT_MOUSE' undeclared
> (first use in this function) ./event/hook/windows/event_c.h:74:22:
> error: request for member 'mi' in something not a structure or union
> ./event/hook/windows/event_c.h:74:25: error: request for member 'dx'
> in something not a structure or union
> ./event/hook/windows/event_c.h:75:22: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:75:25: error: request for member 'dy'
> in something not a structure or union
> ./event/hook/windows/event_c.h:76:22: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:76:25: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:77:22: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:77:25: error: request for member 'time'
> in something not a structure or union
> ./event/hook/windows/event_c.h:80:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:80:26: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:84:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:84:26: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:88:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:88:26: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:92:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:92:26: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:92:39: error: 'XBUTTON1' undeclared
> (first use in this function) ./event/hook/windows/event_c.h:93:23:
> error: request for member 'mi' in something not a structure or union
> ./event/hook/windows/event_c.h:93:26: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:93:40: error: 'MOUSEEVENTF_XDOWN'
> undeclared (first use in this function)
> ./event/hook/windows/event_c.h:97:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:97:26: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:97:39: error: 'XBUTTON2' undeclared
> (first use in this function) ./event/hook/windows/event_c.h:98:23:
> error: request for member 'mi' in something not a structure or union
> ./event/hook/windows/event_c.h:98:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:107:23: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:107:26: error: request for member 'wVk'
> in something not a structure or union
> ./event/hook/windows/event_c.h:108:27: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:108:30: error: request for member 'wVk'
> in something not a structure or union
> ./event/hook/windows/event_c.h:109:24: error: request for member
> 'type' in something not a structure or union
> ./event/hook/windows/event_c.h:110:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:110:27: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:111:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:111:27: error: request for member
> 'wScan' in something not a structure or union
> ./event/hook/windows/event_c.h:112:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:112:27: error: request for member
> 'time' in something not a structure or union
> ./event/hook/windows/event_c.h:123:23: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:123:26: error: request for member 'wVk'
> in something not a structure or union
> ./event/hook/windows/event_c.h:124:27: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:124:30: error: request for member 'wVk'
> in something not a structure or union
> ./event/hook/windows/event_c.h:125:24: error: request for member
> 'type' in something not a structure or union
> ./event/hook/windows/event_c.h:126:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:126:27: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:127:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:127:27: error: request for member 'wVk'
> in something not a structure or union
> ./event/hook/windows/event_c.h:128:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:128:27: error: request for member
> 'wScan' in something not a structure or union
> ./event/hook/windows/event_c.h:129:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:129:27: error: request for member
> 'time' in something not a structure or union
> ./event/hook/windows/event_c.h:141:23: error: request for member
> 'type' in something not a structure or union
> ./event/hook/windows/event_c.h:142:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:142:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:146:25: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:146:28: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:150:25: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:150:28: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:154:25: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:154:28: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:158:25: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:158:28: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:162:25: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:162:28: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:168:26: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:168:29: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:172:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:172:26: error: request for member 'dx'
> in something not a structure or union
> ./event/hook/windows/event_c.h:173:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:173:26: error: request for member 'dy'
> in something not a structure or union
> ./event/hook/windows/event_c.h:175:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:175:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:176:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:176:26: error: request for member
> 'time' in something not a structure or union
> ./event/hook/windows/event_c.h:182:23: error: request for member
> 'type' in something not a structure or union
> ./event/hook/windows/event_c.h:183:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:183:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:183:37: error: 'MOUSEEVENTF_XUP'
> undeclared (first use in this function)
> ./event/hook/windows/event_c.h:187:25: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:187:28: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:191:25: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:191:28: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:195:25: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:195:28: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:199:25: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:199:28: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:203:25: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:203:28: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:209:26: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:209:29: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:213:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:213:26: error: request for member 'dx'
> in something not a structure or union
> ./event/hook/windows/event_c.h:214:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:214:26: error: request for member 'dy'
> in something not a structure or union
> ./event/hook/windows/event_c.h:216:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:216:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:217:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:217:26: error: request for member
> 'time' in something not a structure or union
> ./event/hook/windows/event_c.h:223:23: error: request for member
> 'type' in something not a structure or union
> ./event/hook/windows/event_c.h:224:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:224:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:227:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:227:26: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:229:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:229:26: error: request for member 'dx'
> in something not a structure or union
> ./event/hook/windows/event_c.h:230:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:230:26: error: request for member 'dy'
> in something not a structure or union
> ./event/hook/windows/event_c.h:232:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:232:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:233:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:233:26: error: request for member
> 'time' in something not a structure or union
> ./event/hook/windows/event_c.h:242:23: error: request for member
> 'type' in something not a structure or union
> ./event/hook/windows/event_c.h:243:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:243:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:245:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:245:26: error: request for member 'dx'
> in something not a structure or union
> ./event/hook/windows/event_c.h:246:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:246:26: error: request for member 'dy'
> in something not a structure or union
> ./event/hook/windows/event_c.h:248:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:248:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:249:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:249:26: error: request for member
> 'time' in something not a structure or union
> ./event/hook/windows/event_c.h:274:24: error: request for member
> 'type' in something not a structure or union
> ./event/hook/windows/event_c.h:275:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:275:27: error: request for member 'wVk'
> in something not a structure or union
> ./event/hook/windows/event_c.h:276:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:276:27: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:277:24: error: request for member 'ki'
> in something not a structure or union
> ./event/hook/windows/event_c.h:277:27: error: request for member
> 'time' in something not a structure or union
> ./event/hook/windows/event_c.h:284:22: error: request for member
> 'type' in something not a structure or union
> ./event/hook/windows/event_c.h:285:22: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:285:25: error: request for member 'dx'
> in something not a structure or union
> ./event/hook/windows/event_c.h:286:22: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:286:25: error: request for member 'dy'
> in something not a structure or union
> ./event/hook/windows/event_c.h:287:22: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:287:25: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:288:22: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:288:25: error: request for member
> 'time' in something not a structure or union
> ./event/hook/windows/event_c.h:294:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:294:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:298:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:298:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:302:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:302:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:306:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:306:26: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:307:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:307:26: error: request for member
> 'dwFlags' in something not a structure or union
> ./event/hook/windows/event_c.h:311:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:311:26: error: request for member
> 'mouseData' in something not a structure or union
> ./event/hook/windows/event_c.h:312:23: error: request for member 'mi'
> in something not a structure or union
> ./event/hook/windows/event_c.h:312:26: error: request for member
> 'dwFlags' in something not a structure or union
>

**Comment by vCaesar** [comment] 2016-11-25 07:13
Your system is windows 10 (64 bit),why use "mingw"(32bit)  and  1.7.3 (x86)?

**Comment by vCaesar** [comment] 2016-11-26 06:27
Closing because there is no obvious robotgo problem. If you are convinced there is a robotgo problem, please tell us precisely how we can reproduce the problem ourselves.

**Closed** 2016-11-26 06:26 UTC
