### ISSUE TITLE
go get github.com/go-vgo/robotgo is failed.

### ISSUE THREAD

**Issue by haphupan** [go-vgo/robotgo#437] opened 2022-01-18 09:21 UTC
- Robotgo version (or commit ref):
- Go version:1.14.6
- Gcc version:10.2.0_2
- Operating system and bit:darwin/amd64
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

- Log gist:

## Description
```
➜ go get github.com/go-vgo/robotgo
# github.com/vcaesar/gops
vcaesar/gops/ps.go:160:2: cannot use []string value as type string in return argument
```

**Comment by vcaesar** [comment] 2022-01-19 16:47
Closing is due to can't reproduce.

**Closed by vcaesar** 2022-01-19 16:47 UTC
