### ISSUE TITLE
event/goEvent.h file not found

### ISSUE THREAD

**Issue by simicn** [go-vgo/robotgo#174] opened 2018-10-16 11:08 UTC
- Robotgo version (or commit ref):
 v0.60.0 6f0557305893c33da9ddb8f8aac687653ec074e8
- Go version:
`go version go1.11 darwin/amd64`
- Gcc version:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix

```
- Operating system and bit:
```
macOS High Sierra
10.13.6
```
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:
run the [mouse example](https://github.com/go-vgo/robotgo/blob/master/examples/mouse/main.go ) via
```Go
go run main.go
```
- Log gist:

```
github.com/robotn/gohook
../../vendor/github.com/robotn/gohook/hook.go:22:10: fatal error: 'event/goEvent.h' file not found
#include "event/goEvent.h"
1 error generated.

```

**Comment by vcaesar** [comment] 2018-10-17 16:14
Closing is due to can't reproduce. Please make sure xcode-select tool is installed correctly.

**Closed** 2018-10-17 16:29 UTC

**Comment by simicn** [comment] 2018-10-18 15:37
> Please make sure xcode-select tool is installed correctly.

xcode-select tool is installed
![image](https://user-images.githubusercontent.com/902283/47166300-6f0ed700-d32e-11e8-8f43-43ba2799ba2f.png)
![image](https://user-images.githubusercontent.com/902283/47166338-89e14b80-d32e-11e8-9eef-93631202abe3.png)
![image](https://user-images.githubusercontent.com/902283/47166383-a54c5680-d32e-11e8-8361-49e1b337d21a.png)

**Comment by wilderchen** [comment] 2019-12-20 06:53
I have encountered the same problem as described above. Are there anyone can help to solve the problem?

**Comment by Zyx-A** [comment] 2020-04-02 15:04
我也遇到相同的报错，输出的日志也是一样的。
请问大家有解决吗？

我的操作系统是 CentOS 7.6

并且要求安装的依赖，都已经安装，安装的版本如下：
``` shell
libxkbcommon-devel-0.7.1-1.ky3.kb5.x86_64 已安装并且是最新版本
libXtst-devel-1.2.3-1.ky3.kb5.x86_64 已安装并且是最新版本
libxkbcommon-x11-devel-0.7.1-1.ky3.kb5.x86_64 已安装并且是最新版本
xorg-x11-xkb-utils-devel-7.7-14.ky3.kb2.x86_64 已安装并且是最新版本
2:libpng-devel-1.5.13-7.ky3.kb5.x86_64 已安装并且是最新版本
xsel-1.2.0-15.ky3.kb1.x86_64 已安装并且是最新版本
xclip-0.12-5.ky3.kb1.x86_64 已安装并且是最新版本
```

并且我使用下面的这三种命令，都会报错：
``` shell
$ go build -ldflags '-extldflags "-static"' -o X
$ xgo --targets=linux/amd64 -ldflags '-extldflags "-static"' -o X .
# github.com/robotn/gohook
../../github.com/robotn/gohook/hook.go:22:10: fatal error: event/goEvent.h: No such file or directory
 #include "event/goEvent.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.


$ go get github.com/go-vgo/robotgo
# github.com/robotn/gohook
/home/go/src/github.com/robotn/gohook/hook.go:22:27: fatal error: event/goEvent.h: No such file or directory
 #include "event/goEvent.h"
                           ^
compilation terminated.

```

涉及文件的部分代码如下：
``` shell
$ sed -n '8,28'p /home/go/src/github.com/robotn/gohook/hook.go
// option. This file may not be copied, modified, or distributed
// except according to those terms.

package hook

/*
#cgo darwin CFLAGS: -x objective-c -Wno-deprecated-declarations
#cgo darwin LDFLAGS: -framework Cocoa

#cgo linux CFLAGS:-I/usr/src
#cgo linux LDFLAGS: -L/usr/src -lX11 -lXtst
#cgo linux LDFLAGS: -lX11-xcb -lxcb -lxcb-xkb -lxkbcommon -lxkbcommon-x11
//#cgo windows LDFLAGS: -lgdi32 -luser32

#include "event/goEvent.h"
*/
import "C"

import (
	"fmt"
	"sync"

```

但是使用下面这条命令，则没有任何问题，可以正常编译：
``` shell
go build
```

我的golang版本为：
``` shell
go version go1.13.6 linux/amd64
```

**Comment by Szymongib** [comment] 2020-09-03 09:28
I have stumbled upon this issue myself and after some research, I have found that it is the case when using Go modules as directories that do not contain any `*.go` files are not downloaded to `vendor`.

To solve the problem I used a tool like https://github.com/goware/modvendor.
To install the tool, run:
```
go get -u github.com/goware/modvendor
```
And then run in your project directory:
```
go mod vendor
modvendor -copy="**/*.c **/*.h **/*.proto" -v
```

**Comment by isAlbertYu** [comment] 2020-10-26 06:38
# github.com/robotn/gohook
..\vendor\github.com\robotn\gohook\hook.go:22:10: fatal error: event/goEvent.h: No such file or directory
 #include "event/goEvent.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by ansonhorse** [comment] 2020-12-25 11:20
> I have stumbled upon this issue myself and after some research, I have found that it is the case when using Go modules as directories that do not contain any `*.go` files are not downloaded to `vendor`.
> 
> To solve the problem I used a tool like https://github.com/goware/modvendor.
> To install the tool, run:
> 
> ```
> go get -u github.com/goware/modvendor
> ```
> 
> And then run in your project directory:
> 
> ```
> go mod vendor
> modvendor -copy="**/*.c **/*.h **/*.proto" -v
> ```

Thanks. I try your solution and it worked.

**Comment by ficapy** [comment] 2021-03-13 02:31
try
```
go clean -modcache
```
and then
```
go get ./...
go build
```

**Comment by svirmi** [comment] 2022-08-03 06:42
In my case (I am using xubuntu), the problem was with installing/updating dependencies command -
`sudo apt install libx11-dev xorg-dev libxtst-dev libpng++-dev`
 Software updater was set to fetch OS packages from local country server but there were missing or outdated packages.
After I set it to Main server , all required packages were downloaded and installed properly and the error gone.
Before that I run 
`go clean -modcache`
and then
`go get ./...
go build`
as @ficapy recommended

**Comment by drgrib** [comment] 2023-02-25 18:48
None of this worked for me on a package I added `robotgo` to that I then tried to import to GCP appengine server code. I ended up just removing `robotgo` from the imported package.
