### ISSUE TITLE
fatal error: event/goEvent.h: No such file or directory

### ISSUE THREAD

**Issue by chuyijia** [go-vgo/robotgo#530] opened 2022-08-30 01:38 UTC
- Robotgo version (or commit ref):lates
- Go version:1.17.2
- Gcc version:8.1.0 
- Operating system and bit:Windows10
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [√ ] No
  - [x] Not relevant
- Provide example code:

```Go
func main() {
	rebot.AddMousePos(100, 200)
}
```
- Log gist:

## Description
it report fatal error: event/goEvent.h: No such file or directory
...

**Comment by vcaesar** [comment] 2023-01-16 08:11
Closing is due to can't reproduce.

**Closed by vcaesar** 2023-01-16 08:11 UTC
