### ISSUE TITLE
CaptureScreen() no screen scale judgment

### ISSUE THREAD

**Issue by isBoom** [go-vgo/robotgo#242] opened 2019-11-24 09:18 UTC
With respect to CaptureScreen function, if no parameters are filled in and the screen scale is not 100%, the intercept is not full screen, which is equivalent to calling CaptureScreen (0,0, width* zoom, height* zoom), so that the block is not full screen.

**Comment by vcaesar** [comment] 2019-11-25 17:29
Closed because of duplicates #129 and #135, the current zoom ratio only supports windows, the plan has not been updated yet.

**Comment by vcaesar** [comment] 2019-11-25 17:32
May update code and other platform support in the future.

**Comment by vcaesar** [comment] 2019-12-24 19:45
Closing is due to can't reproduce on windows7, and duplicates #129 and #135, call api processing by yourself.

**Closed by vcaesar** 2019-12-24 19:45 UTC
Labels: enhancement, question
